### ISSUE TITLE
What is tf.slice doing here?

### ISSUE THREAD

**Issue by vanangamudi** [fuhuamosi/MatchLstm#2]
Hi,

https://github.com/fuhuamosi/MatchLstm/blob/master/model/match_lstm.py#L119

` h_s_j = tf.slice(h_s, begin=[0, 0], size=[length_s, self._embedding_size])`

Doesn't it return the whole tensor back?

**Comment by fuhuamosi** [comment]
@vanangamudi Actually, h_s's tensor shape is [50, 300](50 is the maximum length), which means that it contains 'pad' in the tail of the sequence. But through slice method, h_s_j's tensor shape becomes [X, 300](X is the original sentence length),which cut off the 'pad' part.
